"""Initial tables

Revision ID: 95de0d3a798e
Revises: 
Create Date: 2025-12-30 19:19:04.272011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95de0d3a798e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('sdk', sa.String(length=16), nullable=True),
    sa.Column('service_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_build_at', sa.DateTime(), nullable=True),
    sa.Column('build_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('prds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prds_filename'), 'prds', ['filename'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('prd_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['prd_id'], ['prds.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_name'), 'builds', ['name'], unique=False)
    op.create_index('ix_builds_name_started', 'builds', ['name', 'started_at'], unique=False)
    op.create_index('ix_builds_status_started', 'builds', ['status', 'started_at'], unique=False)
    op.create_table('build_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_logs_build_id'), 'build_logs', ['build_id'], unique=False)
    op.create_index('ix_build_logs_build_ts', 'build_logs', ['build_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_build_logs_build_ts', table_name='build_logs')
    op.drop_index(op.f('ix_build_logs_build_id'), table_name='build_logs')
    op.drop_table('build_logs')
    op.drop_index('ix_builds_status_started', table_name='builds')
    op.drop_index('ix_builds_name_started', table_name='builds')
    op.drop_index(op.f('ix_builds_name'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_prds_filename'), table_name='prds')
    op.drop_table('prds')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
